# Site Settings
title: My Resume
url: 'http://oguzeren.org'
baseurl: '/my-cv' #change it according to your repository name
about: False # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: ceramic # blue turquoise green berry orange ceramic


# Profile information
name: Oğuz Kağan EREN
tagline: Works to be a developer
pic: picture.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'I am studying at Dokuz Eylül University. I came to DEU from Mehmet Akif Ersoy University with DGS(I studied two years.). I learned fundamentals of algorithms and basic SQL queries when I am at MAKU. I interested HTML-CSS and designed a few websites. I worked on Microsoft server(DHCP, authorization etc.). I finished the school with 3.7 scores. When I came DEU, The first year, I learned Java and Android developing. The second year,  I learned to work with any Linux distro. Nowadays, I am learning Computer Architecture, React-Native, Python. I continue learning and researching. My motivation is to say If someone can accomplish a job, why can not I succeed? and I know, I can accomplish. '

# Sidebar links
website: oguzeren.org #do not add http://
linkedin: oguzkaganeren
github: oguzkaganeren
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 0.0.0.0
safe: false
